language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

cache:
  apt: true
  pip: false

install:
    - pip install requests
    - python setup.py clean --all
    - python setup.py install

before_script:
    - mkdir -p shippable/codecoverage
    - mkdir -p shippable/testresults

script:
    - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
    - coverage run --branch pocket.py
    - coverage xml -o shippable/codecoverage/coverage.xml pocket.py

notifications:
    email:
        recipients:
            - devops@hypertrack.io
        on_success: change
        on_failure: always

branches:
    only:
        - master
        - develop
