language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

cache:
  apt: true
  pip: false

install:
    - pip install --upgrade coverage pytest unittest2
    - python setup.py clean --all
    - python setup.py install

before_script:
    - mkdir -p travis/codecoverage
    - mkdir -p travis/testresults

script:
    - py.test

notifications:
    email:
        recipients:
            - devops@hypertrack.io
        on_success: change
        on_failure: always

branches:
    only:
        - master
        - develop
