language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"

cache:
  apt: true
  pip: false

install:
    - pip install --upgrade coverage pytest unittest2 pytest-cov
    - python setup.py clean --all
    - python setup.py install
    - python setup.py clean --all

script:
    - py.test --cov=hypertrack

after_success:
    - coveralls

branches:
    only:
        - master
        - develop
